<?php

namespace Database\Seeders;

use App\Models\Package;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PackageNewSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->command->info('🌱 Seeders de Paquetes FIT');

        // 1 clase FIT
        $packageOne = Package::create([
            'name' => '1 clase FIT',
            'slug' => '1-clase-fit',
            'description' => 'Paquete básico de FIT con 1 clase',
            'short_description' => '1 clase FIT válida por 1 mes',
                'classes_quantity' => 1,
            'price_soles' => 55.00,
            'original_price_soles' => 55.00,
            'buy_type' => 'affordable',
                'mode_type' => 'presencial',
                'billing_type' => 'one_time',
            'type' => 'fixed',
            'commercial_type' => 'basic',
            'duration_in_months' => 1,
            'start_date' => null,
            'end_date' => null,
                'is_virtual_access' => false,
                'priority_booking_days' => 1,
            'auto_renewal' => false,
            'is_featured' => false,
            'is_popular' => false,
            'status' => 'active',
            'display_order' => 1,
            'features' => json_encode(['Acceso a clases FIT', 'Equipamiento incluido']),
            'restrictions' => json_encode(['Válido por 30 días']),
            'target_audience' => 'beginner',
            'membership_id' => null,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $packageOne->disciplines()->sync([1, 3, 4]);

        // 8 clases FIT
        $packageEight = Package::create([
            'name' => '8 clase FIT',
            'slug' => '8-clase-fit',
            'description' => 'Paquete mensual de FIT con 8 clases',
            'short_description' => '8 clases FIT válidas por 1 mes',
            'classes_quantity' => 8,
            'price_soles' => 392.00,
            'original_price_soles' => 424.00,
            'buy_type' => 'affordable',
            'mode_type' => 'presencial',
            'billing_type' => 'one_time',
            'type' => 'fixed',
            'commercial_type' => 'basic',
            'duration_in_months' => 1,
            'start_date' => null,
            'end_date' => null,
            'is_virtual_access' => false,
            'priority_booking_days' => 2,
            'auto_renewal' => false,
            'is_featured' => false,
            'is_popular' => true,
            'status' => 'active',
            'display_order' => 2,
            'features' => json_encode(['8 clases FIT', 'Equipamiento incluido', 'Asesoría básica']),
            'restrictions' => json_encode(['Válido por 30 días']),
            'target_audience' => 'intermediate',
            'membership_id' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $packageEight->disciplines()->sync([1, 3, 4]);

        // 12 clases FIT
        $packageTwelve = Package::create([
            'name' => '12 clase FIT',
            'slug' => '12-clase-fit',
            'description' => 'Paquete bimestral de FIT con 12 clases',
            'short_description' => '12 clases FIT válidas por 2 meses',
            'classes_quantity' => 12,
            'price_soles' => 576.00,
            'original_price_soles' => 600.00,
            'buy_type' => 'affordable',
            'mode_type' => 'presencial',
            'billing_type' => 'one_time',
            'type' => 'fixed',
            'commercial_type' => 'basic',
            'duration_in_months' => 2,
            'start_date' => null,
            'end_date' => null,
            'is_virtual_access' => false,
            'priority_booking_days' => 3,
            'auto_renewal' => false,
            'is_featured' => false,
            'is_popular' => false,
            'status' => 'active',
            'display_order' => 3,
            'features' => json_encode(['12 clases FIT', 'Equipamiento incluido', 'Asesoría personalizada']),
            'restrictions' => json_encode(['Válido por 60 días']),
            'target_audience' => 'intermediate',
            'membership_id' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $packageTwelve->disciplines()->sync([1, 3, 4]);

        // 16 clases FIT
        $packageSixteen = Package::create([
            'name' => '16 clase FIT',
            'slug' => '16-clase-fit',
            'description' => 'Paquete trimestral de FIT con 16 clases',
            'short_description' => '16 clases FIT válidas por 3 meses',
            'classes_quantity' => 16,
            'price_soles' => 752.00,
            'original_price_soles' => 784.00,
            'buy_type' => 'affordable',
            'mode_type' => 'presencial',
            'billing_type' => 'one_time',
            'type' => 'fixed',
            'commercial_type' => 'basic',
            'duration_in_months' => 3,
            'start_date' => null,
            'end_date' => null,
            'is_virtual_access' => false,
            'priority_booking_days' => 4,
            'auto_renewal' => false,
            'is_featured' => false,
            'is_popular' => false,
            'status' => 'active',
            'display_order' => 4,
            'features' => json_encode(['16 clases FIT', 'Equipamiento incluido', 'Asesoría personalizada']),
            'restrictions' => json_encode(['Válido por 90 días']),
            'target_audience' => 'intermediate',
            'membership_id' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $packageSixteen->disciplines()->sync([1, 3, 4]);

        // 20 clases FIT
        $packageTwenty = Package::create([
            'name' => '20 clase FIT',
            'slug' => '20-clase-fit',
            'description' => 'Paquete cuatrimestral de FIT con 20 clases',
            'short_description' => '20 clases FIT válidas por 4 meses',
            'classes_quantity' => 20,
            'price_soles' => 920.00,
            'original_price_soles' => 960.00,
            'buy_type' => 'affordable',
            'mode_type' => 'presencial',
            'billing_type' => 'one_time',
            'type' => 'fixed',
            'commercial_type' => 'basic',
            'duration_in_months' => 4,
            'start_date' => null,
            'end_date' => null,
            'is_virtual_access' => false,
            'priority_booking_days' => 5,
            'auto_renewal' => false,
            'is_featured' => false,
            'is_popular' => false,
            'status' => 'active',
            'display_order' => 5,
            'features' => json_encode(['20 clases FIT', 'Equipamiento incluido', 'Asesoría personalizada', 'Prioridad en reservas']),
            'restrictions' => json_encode(['Válido por 120 días']),
            'target_audience' => 'advanced',
            'membership_id' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $packageTwenty->disciplines()->sync([1, 3, 4]);

        // 24 clases FIT (con membership_id = 2)
        $packageTwentyFour = Package::create([
            'name' => '24 clase FIT',
            'slug' => '24-clase-fit',
            'description' => 'Paquete semestral de FIT con 24 clases',
            'short_description' => '24 clases FIT válidas por 6 meses',
            'classes_quantity' => 24,
            'price_soles' => 1080.00,
            'original_price_soles' => 1104.00,
            'buy_type' => 'affordable',
            'mode_type' => 'presencial',
            'billing_type' => 'one_time',
            'type' => 'fixed',
            'commercial_type' => 'offer',
            'duration_in_months' => 6,
            'start_date' => null,
            'end_date' => null,
            'is_virtual_access' => false,
            'priority_booking_days' => 5,
                'auto_renewal' => false,
                'is_featured' => true,
                'is_popular' => false,
                'status' => 'active',
            'display_order' => 6,
            'features' => json_encode(['24 clases FIT', 'Equipamiento incluido', 'Asesoría personalizada', 'Prioridad en reservas']),
            'restrictions' => json_encode(['Válido por 6 meses']),
            'target_audience' => 'advanced',
            'membership_id' => 2,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $packageTwentyFour->disciplines()->sync([1, 3, 4]);

        // 40 clases FIT (con membership_id = 3)
        $packageForty = Package::create([
            'name' => '40 clase FIT',
            'slug' => '40-clase-fit',
            'description' => 'Paquete anual de FIT con 40 clases',
            'short_description' => '40 clases FIT válidas por 1 año',
            'classes_quantity' => 40,
            'price_soles' => 1520.00,
            'original_price_soles' => 1800.00,
            'buy_type' => 'affordable',
            'mode_type' => 'presencial',
            'billing_type' => 'one_time',
            'type' => 'fixed',
            'commercial_type' => 'basic',
            'duration_in_months' => 12,
            'start_date' => null,
            'end_date' => null,
            'is_virtual_access' => false,
            'priority_booking_days' => 7,
            'auto_renewal' => false,
            'is_featured' => false,
            'is_popular' => false,
            'status' => 'active',
            'display_order' => 7,
            'features' => json_encode(['40 clases FIT', 'Equipamiento incluido', 'Asesoría personalizada', 'Máxima prioridad en reservas', 'Acceso a eventos especiales']),
            'restrictions' => json_encode(['Válido por 1 año']),
            'target_audience' => 'advanced',
            'membership_id' => 3,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $packageForty->disciplines()->sync([1, 3, 4]);

        // ========== PAQUETES FIT CON MEMBRESÍA ==========

        // 1 clase FIT - Membresía
        $packageOneMembership = Package::create([
            'name' => '1 clase FIT - Membresía',
            'slug' => '1-clase-fit-membresia',
            'description' => 'Paquete básico de FIT con 1 clase y membresía',
            'short_description' => '1 clase FIT con membresía válida por 1 mes',
            'classes_quantity' => 1,
            'price_soles' => 55.00,
            'original_price_soles' => 55.00,
            'buy_type' => 'affordable',
            'mode_type' => 'presencial',
            'billing_type' => 'one_time',
            'type' => 'fixed',
            'commercial_type' => 'basic',
            'duration_in_months' => 1,
            'start_date' => null,
            'end_date' => null,
            'is_virtual_access' => false,
            'priority_booking_days' => 1,
            'auto_renewal' => false,
            'is_featured' => false,
            'is_popular' => false,
            'status' => 'active',
            'display_order' => 8,
            'features' => json_encode(['Acceso a clases FIT', 'Equipamiento incluido', 'Beneficios de membresía']),
            'restrictions' => json_encode(['Válido por 30 días']),
                'target_audience' => 'beginner',
            'membership_id' => null,
            'is_membresia' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $packageOneMembership->disciplines()->sync([1, 3, 4]);

        // 8 clases FIT - Membresía
        $packageEightMembership = Package::create([
            'name' => '8 clase FIT - Membresía',
            'slug' => '8-clase-fit-membresia',
            'description' => 'Paquete mensual de FIT con 8 clases y membresía',
            'short_description' => '8 clases FIT con membresía válidas por 1 mes',
            'classes_quantity' => 8,
            'price_soles' => 392.00,
            'original_price_soles' => 424.00,
            'buy_type' => 'affordable',
            'mode_type' => 'presencial',
            'billing_type' => 'one_time',
            'type' => 'fixed',
            'commercial_type' => 'basic',
            'duration_in_months' => 1,
            'start_date' => null,
            'end_date' => null,
            'is_virtual_access' => false,
            'priority_booking_days' => 2,
            'auto_renewal' => false,
            'is_featured' => false,
            'is_popular' => true,
            'status' => 'active',
            'display_order' => 9,
            'features' => json_encode(['8 clases FIT', 'Equipamiento incluido', 'Asesoría básica', 'Beneficios de membresía']),
            'restrictions' => json_encode(['Válido por 30 días']),
            'target_audience' => 'intermediate',
            'membership_id' => 1,
            'is_membresia' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $packageEightMembership->disciplines()->sync([1, 3, 4]);

        // 12 clases FIT - Membresía
        $packageTwelveMembership = Package::create([
            'name' => '12 clase FIT - Membresía',
            'slug' => '12-clase-fit-membresia',
            'description' => 'Paquete mensual de FIT con 12 clases y membresía',
            'short_description' => '12 clases FIT con membresía válidas por 1 mes',
            'classes_quantity' => 12,
            'price_soles' => 576.00,
            'original_price_soles' => 600.00,
            'buy_type' => 'affordable',
            'mode_type' => 'presencial',
            'billing_type' => 'one_time',
            'type' => 'fixed',
            'commercial_type' => 'basic',
            'duration_in_months' => 1,
            'start_date' => null,
            'end_date' => null,
            'is_virtual_access' => false,
            'priority_booking_days' => 3,
            'auto_renewal' => false,
            'is_featured' => false,
            'is_popular' => false,
            'status' => 'active',
            'display_order' => 10,
            'features' => json_encode(['12 clases FIT', 'Equipamiento incluido', 'Asesoría personalizada', 'Beneficios de membresía']),
            'restrictions' => json_encode(['Válido por 30 días']),
            'target_audience' => 'intermediate',
            'membership_id' => 1,
            'is_membresia' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $packageTwelveMembership->disciplines()->sync([1, 3, 4]);

        // 16 clases FIT - Membresía
        $packageSixteenMembership = Package::create([
            'name' => '16 clase FIT - Membresía',
            'slug' => '16-clase-fit-membresia',
            'description' => 'Paquete mensual de FIT con 16 clases y membresía',
            'short_description' => '16 clases FIT con membresía válidas por 1 mes',
            'classes_quantity' => 16,
            'price_soles' => 752.00,
            'original_price_soles' => 784.00,
            'buy_type' => 'affordable',
            'mode_type' => 'presencial',
            'billing_type' => 'one_time',
            'type' => 'fixed',
            'commercial_type' => 'basic',
            'duration_in_months' => 1,
            'start_date' => null,
            'end_date' => null,
            'is_virtual_access' => false,
            'priority_booking_days' => 4,
            'auto_renewal' => false,
            'is_featured' => false,
            'is_popular' => false,
            'status' => 'active',
            'display_order' => 11,
            'features' => json_encode(['16 clases FIT', 'Equipamiento incluido', 'Asesoría personalizada', 'Beneficios de membresía']),
            'restrictions' => json_encode(['Válido por 30 días']),
            'target_audience' => 'intermediate',
            'membership_id' => 1,
            'is_membresia' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $packageSixteenMembership->disciplines()->sync([1, 3, 4]);

        // 20 clases FIT - Membresía
        $packageTwentyMembership = Package::create([
            'name' => '20 clase FIT - Membresía',
            'slug' => '20-clase-fit-membresia',
            'description' => 'Paquete mensual de FIT con 20 clases y membresía',
            'short_description' => '20 clases FIT con membresía válidas por 1 mes',
            'classes_quantity' => 20,
            'price_soles' => 920.00,
            'original_price_soles' => 960.00,
            'buy_type' => 'affordable',
            'mode_type' => 'presencial',
            'billing_type' => 'one_time',
            'type' => 'fixed',
            'commercial_type' => 'basic',
            'duration_in_months' => 1,
            'start_date' => null,
            'end_date' => null,
            'is_virtual_access' => false,
            'priority_booking_days' => 5,
            'auto_renewal' => false,
            'is_featured' => false,
            'is_popular' => false,
            'status' => 'active',
            'display_order' => 12,
            'features' => json_encode(['20 clases FIT', 'Equipamiento incluido', 'Asesoría personalizada', 'Prioridad en reservas', 'Beneficios de membresía']),
            'restrictions' => json_encode(['Válido por 30 días']),
            'target_audience' => 'advanced',
            'membership_id' => 1,
            'is_membresia' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $packageTwentyMembership->disciplines()->sync([1, 3, 4]);

        // 24 clases FIT - Membresía (con membership_id = 2)
        $packageTwentyFourMembership = Package::create([
            'name' => '24 clase FIT - Membresía',
            'slug' => '24-clase-fit-membresia',
            'description' => 'Paquete mensual de FIT con 24 clases y membresía',
            'short_description' => '24 clases FIT con membresía válidas por 1 mes',
            'classes_quantity' => 24,
            'price_soles' => 1080.00,
            'original_price_soles' => 1104.00,
            'buy_type' => 'affordable',
            'mode_type' => 'presencial',
            'billing_type' => 'one_time',
            'type' => 'fixed',
            'commercial_type' => 'offer',
            'duration_in_months' => 1,
            'start_date' => null,
            'end_date' => null,
            'is_virtual_access' => false,
            'priority_booking_days' => 5,
            'auto_renewal' => false,
            'is_featured' => true,
            'is_popular' => false,
            'status' => 'active',
            'display_order' => 13,
            'features' => json_encode(['24 clases FIT', 'Equipamiento incluido', 'Asesoría personalizada', 'Prioridad en reservas', 'Beneficios de membresía']),
            'restrictions' => json_encode(['Válido por 30 días']),
            'target_audience' => 'advanced',
            'membership_id' => 2,
            'is_membresia' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $packageTwentyFourMembership->disciplines()->sync([1, 3, 4]);

        // 40 clases FIT - Membresía (con membership_id = 3)
        $packageFortyMembership = Package::create([
            'name' => '40 clase FIT - Membresía',
            'slug' => '40-clase-fit-membresia',
            'description' => 'Paquete mensual de FIT con 40 clases y membresía',
            'short_description' => '40 clases FIT con membresía válidas por 1 mes',
            'classes_quantity' => 40,
            'price_soles' => 1520.00,
            'original_price_soles' => 1800.00,
            'buy_type' => 'affordable',
            'mode_type' => 'presencial',
            'billing_type' => 'one_time',
            'type' => 'fixed',
            'commercial_type' => 'basic',
            'duration_in_months' => 1,
            'start_date' => null,
            'end_date' => null,
            'is_virtual_access' => false,
            'priority_booking_days' => 7,
            'auto_renewal' => false,
            'is_featured' => false,
            'is_popular' => false,
            'status' => 'active',
            'display_order' => 14,
            'features' => json_encode(['40 clases FIT', 'Equipamiento incluido', 'Asesoría personalizada', 'Máxima prioridad en reservas', 'Acceso a eventos especiales', 'Beneficios de membresía']),
            'restrictions' => json_encode(['Válido por 30 días']),
            'target_audience' => 'advanced',
            'membership_id' => 3,
            'is_membresia' => true,
                'created_at' => now(),
                'updated_at' => now(),
        ]);
        $packageFortyMembership->disciplines()->sync([1, 3, 4]);

        // ========== PAQUETES REFORMER CON MEMBRESÍA ==========

        // 1 clase Reformer
        $packageOneReformer = Package::create([
            'name' => '1 clase Reformer',
            'slug' => '1-clase-reformer',
            'description' => 'Paquete básico de Reformer con 1 clase',
            'short_description' => '1 clase Reformer válida por 1 mes',
                'classes_quantity' => 1,
            'price_soles' => 69.00,
            'original_price_soles' => 80.00,
            'buy_type' => 'affordable',
                'mode_type' => 'presencial',
                'billing_type' => 'one_time',
            'type' => 'fixed',
            'commercial_type' => 'basic',
            'duration_in_months' => 1,
            'start_date' => null,
            'end_date' => null,
                'is_virtual_access' => false,
                'priority_booking_days' => 1,
            'auto_renewal' => false,
            'is_featured' => false,
            'is_popular' => false,
            'status' => 'active',
            'display_order' => 15,
            'features' => json_encode(['Acceso a clases Reformer', 'Equipamiento especializado', 'Instrucción personalizada']),
            'restrictions' => json_encode(['Válido por 30 días']),
            'target_audience' => 'beginner',
            'membership_id' => 1,
            'is_membresia' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $packageOneReformer->disciplines()->sync([2]);

        // 4 clases Reformer
        $packageFourReformer = Package::create([
            'name' => '4 clase Reformer',
            'slug' => '4-clase-reformer',
            'description' => 'Paquete mensual de Reformer con 4 clases',
            'short_description' => '4 clases Reformer válidas por 1 mes',
            'classes_quantity' => 4,
            'price_soles' => 250.00,
            'original_price_soles' => 300.00,
            'buy_type' => 'affordable',
            'mode_type' => 'presencial',
            'billing_type' => 'one_time',
            'type' => 'fixed',
            'commercial_type' => 'basic',
            'duration_in_months' => 1,
            'start_date' => null,
            'end_date' => null,
            'is_virtual_access' => false,
            'priority_booking_days' => 2,
            'auto_renewal' => false,
            'is_featured' => false,
            'is_popular' => true,
            'status' => 'active',
            'display_order' => 16,
            'features' => json_encode(['4 clases Reformer', 'Equipamiento especializado', 'Instrucción personalizada', 'Evaluación de progreso']),
            'restrictions' => json_encode(['Válido por 30 días']),
            'target_audience' => 'intermediate',
            'membership_id' => 1,
            'is_membresia' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $packageFourReformer->disciplines()->sync([2]);

        // 8 clases Reformer
        $packageEightReformer = Package::create([
            'name' => '8 clase Reformer',
            'slug' => '8-clase-reformer',
            'description' => 'Paquete mensual de Reformer con 8 clases',
            'short_description' => '8 clases Reformer válidas por 1 mes',
            'classes_quantity' => 8,
            'price_soles' => 450.00,
            'original_price_soles' => 592.00,
            'buy_type' => 'affordable',
            'mode_type' => 'presencial',
            'billing_type' => 'one_time',
            'type' => 'fixed',
            'commercial_type' => 'basic',
            'duration_in_months' => 1,
            'start_date' => null,
            'end_date' => null,
            'is_virtual_access' => false,
            'priority_booking_days' => 3,
            'auto_renewal' => false,
            'is_featured' => false,
            'is_popular' => false,
            'status' => 'active',
            'display_order' => 17,
            'features' => json_encode(['8 clases Reformer', 'Equipamiento especializado', 'Instrucción personalizada', 'Evaluación de progreso']),
            'restrictions' => json_encode(['Válido por 30 días']),
            'target_audience' => 'intermediate',
            'membership_id' => 1,
            'is_membresia' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $packageEightReformer->disciplines()->sync([2]);

        // 12 clases Reformer
        $packageTwelveReformer = Package::create([
            'name' => '12 clase Reformer',
            'slug' => '12-clase-reformer',
            'description' => 'Paquete mensual de Reformer con 12 clases',
            'short_description' => '12 clases Reformer válidas por 1 mes',
            'classes_quantity' => 12,
            'price_soles' => 540.00,
            'original_price_soles' => 876.00,
            'buy_type' => 'affordable',
            'mode_type' => 'presencial',
            'billing_type' => 'one_time',
            'type' => 'fixed',
            'commercial_type' => 'basic',
            'duration_in_months' => 1,
            'start_date' => null,
            'end_date' => null,
            'is_virtual_access' => false,
            'priority_booking_days' => 4,
            'auto_renewal' => false,
            'is_featured' => false,
            'is_popular' => false,
            'status' => 'active',
            'display_order' => 18,
            'features' => json_encode(['12 clases Reformer', 'Equipamiento especializado', 'Instrucción personalizada', 'Evaluación de progreso', 'Plan personalizado']),
            'restrictions' => json_encode(['Válido por 30 días']),
            'target_audience' => 'intermediate',
            'membership_id' => 1,
            'is_membresia' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $packageTwelveReformer->disciplines()->sync([2]);

        // 20 clases Reformer (con membership_id = 2)
        $packageTwentyReformer = Package::create([
            'name' => '20 clase Reformer',
            'slug' => '20-clase-reformer',
            'description' => 'Paquete mensual de Reformer con 20 clases',
            'short_description' => '20 clases Reformer válidas por 1 mes',
            'classes_quantity' => 20,
            'price_soles' => 950.00,
            'original_price_soles' => 1340.00,
            'buy_type' => 'affordable',
            'mode_type' => 'presencial',
            'billing_type' => 'one_time',
            'type' => 'fixed',
            'commercial_type' => 'offer',
            'duration_in_months' => 1,
            'start_date' => null,
            'end_date' => null,
            'is_virtual_access' => false,
            'priority_booking_days' => 5,
                'auto_renewal' => false,
                'is_featured' => true,
                'is_popular' => false,
                'status' => 'active',
            'display_order' => 19,
            'features' => json_encode(['20 clases Reformer', 'Equipamiento especializado', 'Instrucción personalizada', 'Evaluación de progreso', 'Plan personalizado', 'Prioridad en reservas']),
            'restrictions' => json_encode(['Válido por 30 días']),
            'target_audience' => 'advanced',
            'membership_id' => 2,
            'is_membresia' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $packageTwentyReformer->disciplines()->sync([2]);

        // 40 clases Reformer (con membership_id = 3)
        $packageFortyReformer = Package::create([
            'name' => '40 clase Reformer',
            'slug' => '40-clase-reformer',
            'description' => 'Paquete mensual de Reformer con 40 clases',
            'short_description' => '40 clases Reformer válidas por 1 mes',
            'classes_quantity' => 40,
            'price_soles' => 1800.00,
            'original_price_soles' => 2400.00,
            'buy_type' => 'affordable',
            'mode_type' => 'presencial',
            'billing_type' => 'one_time',
            'type' => 'fixed',
            'commercial_type' => 'basic',
            'duration_in_months' => 1,
            'start_date' => null,
            'end_date' => null,
            'is_virtual_access' => false,
            'priority_booking_days' => 7,
            'auto_renewal' => false,
            'is_featured' => false,
            'is_popular' => false,
            'status' => 'active',
            'display_order' => 20,
            'features' => json_encode(['40 clases Reformer', 'Equipamiento especializado', 'Instrucción personalizada', 'Evaluación de progreso', 'Plan personalizado', 'Máxima prioridad en reservas', 'Acceso a eventos especiales', 'Sesiones de evaluación trimestrales']),
            'restrictions' => json_encode(['Válido por 30 días']),
            'target_audience' => 'advanced',
            'membership_id' => 3,
            'is_membresia' => true,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $packageFortyReformer->disciplines()->sync([2]);

        // ========== PAQUETES REFORMER REGULARES (SIN MEMBRESÍA) ==========

        // 1 clase Reformer - Regular
        $packageOneReformerRegular = Package::create([
            'name' => '1 clase Reformer',
            'slug' => '1-clase-reformer-regular',
            'description' => 'Paquete básico de Reformer con 1 clase',
            'short_description' => '1 clase Reformer válida por 1 mes',
            'classes_quantity' => 1,
            'price_soles' => 69.00,
            'original_price_soles' => 80.00,
            'buy_type' => 'affordable',
            'mode_type' => 'presencial',
            'billing_type' => 'one_time',
            'type' => 'fixed',
            'commercial_type' => 'basic',
            'duration_in_months' => 1,
            'start_date' => null,
            'end_date' => null,
            'is_virtual_access' => false,
            'priority_booking_days' => 1,
            'auto_renewal' => false,
            'is_featured' => false,
            'is_popular' => false,
            'status' => 'active',
            'display_order' => 21,
            'features' => json_encode(['Acceso a clases Reformer', 'Equipamiento especializado', 'Instrucción personalizada']),
            'restrictions' => json_encode(['Válido por 30 días']),
                'target_audience' => 'beginner',
            'membership_id' => 1,
            'is_membresia' => false,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $packageOneReformerRegular->disciplines()->sync([2]);

        // 4 clases Reformer - Regular
        $packageFourReformerRegular = Package::create([
            'name' => '4 clase Reformer',
            'slug' => '4-clase-reformer-regular',
            'description' => 'Paquete mensual de Reformer con 4 clases',
            'short_description' => '4 clases Reformer válidas por 1 mes',
            'classes_quantity' => 4,
            'price_soles' => 250.00,
            'original_price_soles' => 300.00,
            'buy_type' => 'affordable',
            'mode_type' => 'presencial',
            'billing_type' => 'one_time',
            'type' => 'fixed',
            'commercial_type' => 'basic',
            'duration_in_months' => 1,
            'start_date' => null,
            'end_date' => null,
            'is_virtual_access' => false,
            'priority_booking_days' => 2,
            'auto_renewal' => false,
            'is_featured' => false,
            'is_popular' => true,
            'status' => 'active',
            'display_order' => 22,
            'features' => json_encode(['4 clases Reformer', 'Equipamiento especializado', 'Instrucción personalizada', 'Evaluación de progreso']),
            'restrictions' => json_encode(['Válido por 30 días']),
            'target_audience' => 'intermediate',
            'membership_id' => 1,
            'is_membresia' => false,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $packageFourReformerRegular->disciplines()->sync([2]);

        // 8 clases Reformer - Regular
        $packageEightReformerRegular = Package::create([
            'name' => '8 clase Reformer',
            'slug' => '8-clase-reformer-regular',
            'description' => 'Paquete bimestral de Reformer con 8 clases',
            'short_description' => '8 clases Reformer válidas por 2 meses',
            'classes_quantity' => 8,
            'price_soles' => 450.00,
            'original_price_soles' => 592.00,
            'buy_type' => 'affordable',
            'mode_type' => 'presencial',
            'billing_type' => 'one_time',
            'type' => 'fixed',
            'commercial_type' => 'basic',
            'duration_in_months' => 2,
            'start_date' => null,
            'end_date' => null,
            'is_virtual_access' => false,
            'priority_booking_days' => 3,
            'auto_renewal' => false,
            'is_featured' => false,
            'is_popular' => false,
            'status' => 'active',
            'display_order' => 23,
            'features' => json_encode(['8 clases Reformer', 'Equipamiento especializado', 'Instrucción personalizada', 'Evaluación de progreso']),
            'restrictions' => json_encode(['Válido por 60 días']),
            'target_audience' => 'intermediate',
            'membership_id' => 1,
            'is_membresia' => false,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $packageEightReformerRegular->disciplines()->sync([2]);

        // 12 clases Reformer - Regular
        $packageTwelveReformerRegular = Package::create([
            'name' => '12 clase Reformer',
            'slug' => '12-clase-reformer-regular',
            'description' => 'Paquete trimestral de Reformer con 12 clases',
            'short_description' => '12 clases Reformer válidas por 3 meses',
            'classes_quantity' => 12,
            'price_soles' => 540.00,
            'original_price_soles' => 876.00,
            'buy_type' => 'affordable',
            'mode_type' => 'presencial',
            'billing_type' => 'one_time',
            'type' => 'fixed',
            'commercial_type' => 'basic',
            'duration_in_months' => 3,
            'start_date' => null,
            'end_date' => null,
            'is_virtual_access' => false,
            'priority_booking_days' => 4,
            'auto_renewal' => false,
            'is_featured' => false,
            'is_popular' => false,
            'status' => 'active',
            'display_order' => 24,
            'features' => json_encode(['12 clases Reformer', 'Equipamiento especializado', 'Instrucción personalizada', 'Evaluación de progreso', 'Plan personalizado']),
            'restrictions' => json_encode(['Válido por 90 días']),
            'target_audience' => 'intermediate',
            'membership_id' => 1,
            'is_membresia' => false,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $packageTwelveReformerRegular->disciplines()->sync([2]);

        // 20 clases Reformer - Regular (con membership_id = 2)
        $packageTwentyReformerRegular = Package::create([
            'name' => '20 clase Reformer',
            'slug' => '20-clase-reformer-regular',
            'description' => 'Paquete semestral de Reformer con 20 clases',
            'short_description' => '20 clases Reformer válidas por 6 meses',
            'classes_quantity' => 20,
            'price_soles' => 950.00,
            'original_price_soles' => 1340.00,
            'buy_type' => 'affordable',
            'mode_type' => 'presencial',
            'billing_type' => 'one_time',
            'type' => 'fixed',
            'commercial_type' => 'offer',
            'duration_in_months' => 6,
            'start_date' => null,
            'end_date' => null,
            'is_virtual_access' => false,
            'priority_booking_days' => 5,
            'auto_renewal' => false,
            'is_featured' => true,
            'is_popular' => false,
            'status' => 'active',
            'display_order' => 25,
            'features' => json_encode(['20 clases Reformer', 'Equipamiento especializado', 'Instrucción personalizada', 'Evaluación de progreso', 'Plan personalizado', 'Prioridad en reservas']),
            'restrictions' => json_encode(['Válido por 6 meses']),
            'target_audience' => 'advanced',
            'membership_id' => 2,
            'is_membresia' => false,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        $packageTwentyReformerRegular->disciplines()->sync([2]);

        // 40 clases Reformer - Regular (con membership_id = 3)
        $packageFortyReformerRegular = Package::create([
            'name' => '40 clase Reformer',
            'slug' => '40-clase-reformer-regular',
            'description' => 'Paquete anual de Reformer con 40 clases',
            'short_description' => '40 clases Reformer válidas por 1 año',
            'classes_quantity' => 40,
            'price_soles' => 1800.00,
            'original_price_soles' => 2400.00,
            'buy_type' => 'affordable',
            'mode_type' => 'presencial',
            'billing_type' => 'one_time',
            'type' => 'fixed',
            'commercial_type' => 'basic',
            'duration_in_months' => 12,
            'start_date' => null,
            'end_date' => null,
            'is_virtual_access' => false,
            'priority_booking_days' => 7,
            'auto_renewal' => false,
            'is_featured' => false,
            'is_popular' => false,
            'status' => 'active',
            'display_order' => 26,
            'features' => json_encode(['40 clases Reformer', 'Equipamiento especializado', 'Instrucción personalizada', 'Evaluación de progreso', 'Plan personalizado', 'Máxima prioridad en reservas', 'Acceso a eventos especiales', 'Sesiones de evaluación trimestrales']),
            'restrictions' => json_encode(['Válido por 1 año']),
            'target_audience' => 'advanced',
            'membership_id' => 3,
            'is_membresia' => false,
                'created_at' => now(),
                'updated_at' => now(),
        ]);
        $packageFortyReformerRegular->disciplines()->sync([2]);

        $this->command->info('✅ Paquetes FIT y Reformer creados exitosamente');
    }
}
